---
applications:
- name: amsd-casework-production
  services:
    - amsd-casework-production-redis
  env:
    "AAD:Instance": ((aad_instance))
    "AAD:ResourceId": ((aad_resource_id))
    "AAD:TenantId": ((aad_tenant_id))
    username: ((username))
    password: ((password))
