---
applications:
- name: amsd-casework-staging
  routes:
    - route: amsd-casework-staging.london.cloudapps.digital
  services:
    - amsd-casework-staging-redis
  env:
    ASPNETCORE_ENVIRONMENT: Staging
    ASPNETCORE_URLS: http://+:8080
