name: Build and Test

on:
  pull_request:
    branches: [ main ]
        
jobs:
  start-redis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4, 5 ]

    steps:
      - name: Start Redis v${{ matrix.redis-version }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      options: >-
        --health-cmd "redis-cli ping"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  
  build-test:
    needs: start-redis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore ConcernsCaseWork/ConcernsCaseWork.sln
      - name: Build
        run: dotnet build ConcernsCaseWork/ConcernsCaseWork.sln --no-restore
      - name: Test
        run: dotnet test ConcernsCaseWork/ConcernsCaseWork.sln --no-build --verbosity diagnostic