name: Build and Test

on:
  pull_request:
    branches: [ main ]
        
jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore ConcernsCaseWork/ConcernsCaseWork.sln
      - name: Build
        run: dotnet build ConcernsCaseWork/ConcernsCaseWork.sln --no-restore
      - name: Set environment variables
        run: |
          echo "VCAP_SERVICES=$secrets.VCAP_SERVICES" >> $GITHUB_ENV
          echo "TRAMS_API_ENDPOINT=$secrets.TRAMS_API_ENDPOINT" >> $GITHUB_ENV
          echo "TRAMS_API_KEY=$secrets.TRAMS_API_KEY" >> $GITHUB_ENV
      
      - name: Test
        run: dotnet test ConcernsCaseWork/ConcernsCaseWork.sln --no-build --verbosity diagnostic
        env: 
          "VCAP_SERVICES" : ${{ env.VCAP_SERVICES }}
          "trams:api_endpoint" : ${{ env.TRAMS_API_ENDPOINT }}
          "trams:api_key" : ${{ env.TRAMS_API_KEY }}