name: Deploy to Dev

on:
  push:
    branches: [ main ]

env:
  PAAS_URL: https://api.london.cloud.service.gov.uk
  REGISTRY: ghcr.io
  REPO_NAME: dfe-digital/amsd-casework

jobs:
  download_artifact:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Download artifact url
        uses: actions/download-artifact@v2
        with:
          name: artifact-url
          path: ${{ github.workspace }}/artifact/tag.txt
      - shell: bash
        run: |
          value=`cat ${{ github.workspace }}/artifact/tag.txt`
          echo '::set-output name=artifact_tag::$value'
        id: tagurl
  
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Build Frontend
        run: make build-frontend
      
      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli
                
      - name: Deploy Code
        run: |
          cf api ${{ env.PAAS_URL }}
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o dfe -s amsd-casework-dev
          echo "REPO_URL:: ${{ steps.tagurl.outputs.artifact_tag }}"
          cf push amsd-casework-dev --docker-image ${{ steps.tagurl.outputs.artifact_tag }} -f deploy-manifests/dev.yml